source("setup.R")
library(shiny)
source("R/directory.R")
source("R/plot_editor.R")
source("R/plotting.R")
source("R/regression.R")
source("R/logistic_regression.R")
source("R/advanced_regression.R")
source("R/random_forest.R")
source("R/decision_tree.R")
source("R/model_comparison.R")
source("R/svm.R")
source("R/pca.R")
source("R/kmeans.R")
source("R/timeseries.R")

text_only <- data.frame(code = paste0("row-", seq_len(30)), stringsAsFactors = FALSE)
high_cardinality <- data.frame(a = seq_len(30), b = seq_len(30) + 100, c = seq_len(30) + 200)
workdir <- reactive(tempdir())

testServer(analysis_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact() })
testServer(regression_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(logistic_regression_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(advanced_regression_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(random_forest_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(decision_tree_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(model_comparison_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(svm_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(pca_server, args = list(data = reactive(high_cardinality), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(kmeans_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })
testServer(timeseries_server, args = list(data = reactive(text_only), directory = workdir), { session$flushReact(); stopifnot(is.null(result())) })

cat("各分析模块在没有数值字段、预测字段或低类别分组字段时的空选项检查通过。\n")
